# .streamlit/secrets.toml

[snowflake]
account = "SYVEUEV-DQ70641"
user = "YOURSTORYHACKATHON"
password = "Hsy$20305@Ravi"
warehouse = "COMPUTE_WH"
database = "YOURSTORYHACKATHON"
schema = "PUBLIC"
role = "ACCOUNTADMIN"
